In [7]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(a[0])

[1 2 3 4 5]
1


In [9]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(a.ndim)

[1 2 3 4 5]
1


In [18]:
import numpy as np
a=np.array([[1,2,3,4,],[1,3,4,5]])
print(a.ndim)

2


In [17]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
print(a[:3])

[1 2 3]


In [19]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
print(a[3:])

[4 5 6 7 8]


In [20]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
print(a[2:6])

[3 4 5 6]


In [21]:
import numpy as np
d = np.array([[[1, 2, 3, 4, 5],[6,7,8,9,10]],[[11, 12, 13, 14, 15],[16,17,18,19,20]]])
d[1,0,1]


12